# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.vm.define 'alpine36' do |alpine|
        alpine.vm.box = 'qnib/alpine36'
        alpine.vm.provider 'virtualbox' do |vb|
            vb.name = 'alpine3.6'
            vb.cpus = 2
            vb.memory = 2048
            vb.customize [
                'modifyvm', :id,
                '--natdnshostresolver1', 'on',
                '--nic1', 'nat',
                '--cableconnected1', 'on'
            ]
        end
    end
end
