stages:
  – build

builc_rocky8-slurm:
  stage: build
  script:
    – cd rocky8-slurm
    – packer build --force slurm.json
    - vagrant box add --name rocky8-slurm --force output-vagrant/package.box

